const tintColor = '#2f95dc';

export default {
  primary: '#ff4301',
  secondary: '',
  tintColor,
  dark: '#252525',
  black: '#000',
  white: '#fff',
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  success: '#2ecc71',
  dangerActive: '#ed7669',
  danger: '#e74c3c',
  secondary: 'rgba(0,0,0,0.1)',
  prime: '#0073aa',
  info: '#3498db',
};
